#!/bin/bash

echo "Starting Raft KV Store Transaction Demo"
echo "======================================="
echo ""
echo "This demo shows MVCC snapshot isolation:"
echo "- Transactions see a consistent snapshot from when they started"
echo "- Other clients' changes don't affect an active transaction"
echo ""
echo "Instructions:"
echo "1. Start 3 nodes in separate terminals:"
echo "   Terminal 1: ./gradlew run --args=\"node1 5001 node2:5002 node3:5003\""
echo "   Terminal 2: ./gradlew run --args=\"node2 5002 node1:5001 node3:5003\""
echo "   Terminal 3: ./gradlew run --args=\"node3 5003 node1:5001 node2:5002\""
echo ""
echo "2. In Terminal 4, run the client:"
echo "   ./gradlew runClient"
echo ""
echo "3. Try these commands to see MVCC in action:"
echo ""
echo "# Setup"
echo "> put account 1000"
echo "> get account"
echo ""
echo "# Start a transaction (captures current version)"
echo "> begin"
echo "> tget account    # Reads 1000"
echo ""
echo "# In another client terminal, modify the value"
echo "> put account 2000"
echo ""
echo "# Back in the transaction terminal"
echo "> tget account    # Still reads 1000! (snapshot isolation)"
echo "> get account     # Reads 2000 (outside transaction)"
echo "> commit"
echo ""
echo "# Or use the automated demo:"
echo "> txdemo"
echo ""
echo "This demonstrates how MVCC provides snapshot isolation for transactions!"